import test from 'node:test';
import assert from 'node:assert/strict';
import '../../public/yp-web-ai/js/auto-lighting.js';
import '../../public/yp-web-ai/js/template-lighting.js';
import '../../public/yp-web-ai/js/peninsular-templates.js';
import '../../public/yp-web-ai/js/corner-templates.js';
const A=globalThis.YPAutoLighting,L=globalThis.YPTemplateLighting;
function spec(id){const lib=id.startsWith('corner')?YPCornerTemplates:YPPeninsularTemplates,t=lib.templates.find(t=>t.id===id),catalog=[...new Set(t.objects.map(o=>o.catalogId))].map(catalogId=>({catalogId,type:catalogId==='brand-artwork-copy'?'brandCopy':'panel',unitPrice:0}));return lib.build(id,{wallStickers:{back:{},left:{},right:{}},wallStickerFaces:[],assetAttachmentGraph:{attachments:[]}},catalog).spec;}
for(const id of ['corner-timber-lounge','penin-blue-pavilion','penin-orchard'])test(id+' has supported anchors, grouped targets and no screen targets',()=>{
  const s=spec(id),before=structuredClone(s),out=A.generateLightingPlan({spec:s});assert.deepEqual(s,before);assert.equal(out.diagnostics.profile,id);assert.ok(out.diagnostics.mounts.some(m=>m.type==='downlight'));assert.ok(out.suggestions.some(f=>f.fixtureType!=='invisible'));assert.equal(out.diagnostics.targets.some(t=>t.type==='screen'),false);assert.equal(out.diagnostics.targets.filter(t=>t.type==='meeting').length,s.objects.filter(o=>o.catalogId==='table-standard').length);
  for(const f of out.suggestions.filter(f=>f.fixtureType!=='invisible')){assert.ok(f.mountAttachment);assert.equal(f.valid,true);assert.equal(L.resolve(s,f).valid,true);}
  console.log(id,out.suggestions.map(f=>f.fixtureType+':'+f.targetType).join(', '));
});
test('lighting never moves template logos',()=>{const s=spec('corner-timber-lounge');s.logoWallU=1.1;A.applyAutomaticBrandWallLayout(s);A.generateLightingPlan({spec:s});assert.equal(s.logoWallU,1.1);});
test('Peninsular wall mount uses actual 30 cm thickness',()=>{const s=spec('penin-blue-pavilion'),m=L.mounts(s).find(m=>m.face==='back');assert.equal(m.position.z,.15);});
test('approved lights follow their parent, missing parents are flagged not dropped',()=>{
  const s=spec('penin-blue-pavilion'),plan=A.generateLightingPlan({spec:s}),f=plan.suggestions.find(f=>f.mountAttachment?.mountRole==='template-under'&&f.fixtureType!=='invisible');assert.ok(f);const parent=s.objects.find(o=>o.id===f.mountAttachment.parentAssetId);parent.position.x+=.1;const moved=L.resolve(s,f);assert.ok(Math.abs(moved.position.x-f.position.x-.1)<1e-8);
  s.objects=s.objects.filter(o=>o!==parent);s.lighting={...plan,approvedFixtures:[{...f,status:'approved'}],suggestions:[]};const next=A.recalculateLightingPlan({spec:s});assert.equal(next.approvedFixtures.length,1);assert.equal(next.approvedFixtures[0].valid,false);
});
test('manual positions survive recalculation and are not duplicated',()=>{const s=spec('corner-timber-lounge'),plan=A.generateLightingPlan({spec:s}),f=structuredClone(plan.suggestions.find(f=>f.fixtureType!=='invisible'));f.mountAttachment=null;f.source='manual';f.position.x+=.09;s.lighting={...plan,suggestions:[f]};const next=A.generateLightingPlan({spec:s});assert.deepEqual(next.suggestions.find(o=>o.id===f.id).position,f.position);assert.equal(next.suggestions.filter(o=>o.targetAssetId===f.targetAssetId).length,1);});
test('corner mirrors light anchors and targets; round trip is stable within serialized millimetre precision',()=>{const s=spec('corner-timber-lounge');s.lighting=A.generateLightingPlan({spec:s});const left=YPCornerTemplates.mirror(s,'left'),back=YPCornerTemplates.mirror(left,'right');for(let i=0;i<s.lighting.suggestions.length;i++){const original=s.lighting.suggestions[i],f=left.lighting.suggestions[i];assert.ok(Math.abs(f.position.x-(6-original.position.x))<1e-8);assert.ok(Math.abs(L.resolve(left,f).position.x-f.position.x)<.004);assert.ok(Math.abs(back.lighting.suggestions[i].position.x-original.position.x)<1e-8);}});
test('decorative panels cannot become mounts; obstruction blocks the ray',()=>{const s=spec('penin-orchard');assert.equal(L.mounts(s).filter(m=>m.role==='template-under').length,5);s.objects=[{id:'block',size:{w:1,d:1,h:2},position:{x:3,y:0,z:1.5},rotationY:20}];assert.equal(L.blockedSegment(s,{x:3,y:1,z:0},{x:3,y:1,z:3}),true);});
test('unprofiled template keeps the legacy planner',()=>{const s=spec('penin-adventure');assert.equal(L.profile(s),null);assert.equal(A.generateLightingPlan({spec:s}).diagnostics.profile,undefined);});
test('preview-only suggestions cannot become approved equipment',()=>{const s=spec('penin-orchard'),plan=A.generateLightingPlan({spec:s,lighting:{fixturePreference:'invisible'}});assert.ok(plan.suggestions.length);assert.ok(plan.suggestions.every(f=>f.fixtureType==='invisible'));assert.equal(A.approveSuggestions(plan).approvedFixtures.length,0);assert.ok(L.resolve(s,plan.suggestions[0]).validationWarnings.length);});
test('anchor follows yaw and scale, tilted mount becomes ineligible',()=>{const s=spec('penin-blue-pavilion'),f=A.generateLightingPlan({spec:s}).suggestions.find(f=>f.fixtureType==='downlight'),parent=s.objects.find(o=>o.id===f.mountAttachment.parentAssetId);parent.rotationY=90;parent.transform={scale:.8};const r=L.resolve(s,f),u=f.mountAttachment.surfaceUV.u,v=f.mountAttachment.surfaceUV.v;assert.ok(Math.abs(r.position.x-(parent.position.x+(v-.5)*parent.size.d*.8))<1e-9);assert.ok(Math.abs(r.position.z-(parent.position.z-(u-.5)*parent.size.w*.8))<1e-9);parent.rotationX=25;assert.equal(L.resolve(s,f).valid,false);assert.equal(L.mounts(s).some(m=>m.parent===parent.id),false);});
