import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const script=await readFile(new URL('../../public/yp-web-ai/js/template-branding.js',import.meta.url),'utf8');
function setup(){const context={btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary'),unescape,encodeURIComponent,DOMParser:class{parseFromString(){return{documentElement:{getAttribute:()=> '0 0 400 100',innerHTML:'<path d="M0 0h400v100H0z"/>'}};}},YPDefaultLogo:{data:'data:image/svg+xml;base64,'+Buffer.from('<svg/>').toString('base64'),brand:'Yuppie Production'}};vm.createContext(context);vm.runInContext(script,context);return context;}
test('logo composition uses physical aspect and SVG meet, not stretched text',()=>{const c=setup(),data=c.YPTemplateBranding.artwork(null,2,.25),svg=Buffer.from(data.split(',')[1],'base64').toString();assert.match(svg,/viewBox="0 0 1200 150"/);assert.match(svg,/preserveAspectRatio="xMidYMid meet"/);assert.doesNotMatch(svg,/<text/);});
test('new template gets Yuppie; source layout and unrelated saved designs are unchanged',()=>{const c=setup(),t={objects:[{brandLogo:true}]},o={id:'logo',size:{w:1,h:.18,d:.01},position:{x:2,y:2,z:.4},appearance:{}},s={logo:'old',brand:'old',objects:[o]},saved=structuredClone(s),before=JSON.stringify(t),position=JSON.stringify(o.position);c.YPTemplateBranding.apply(s,t);assert.equal(s.logo,c.YPDefaultLogo.data);assert.equal(s.brand,c.YPDefaultLogo.brand);assert.equal(JSON.stringify(t),before);assert.equal(JSON.stringify(o.position),position);assert.equal(saved.logo,'old');assert.equal(saved.brand,'old');});
test('details are per-template opt-ins and preserve object identity, dimensions and groups',()=>{const c=setup(),o={id:'seat',catalogId:'lounge-sofa',groupId:'g',size:{w:1.5,h:.8,d:.7},position:{x:1,y:0,z:1},appearance:{color:'#efede9'}},s={objects:[o]},before=structuredClone(o);c.YPTemplateBranding.apply(s,{objects:[{}]});assert.equal(o.structure.design,'timber-sofa');assert.equal(o.structure.color,'#efede9');assert.deepEqual(o.position,before.position);assert.deepEqual(o.size,before.size);assert.equal(o.groupId,'g');});
